import { app } from 'electron'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { basename, join } from 'path'

/**
 * Inject an OSC 7 cwd-notification hook into the user's shell so the renderer
 * can keep PaneToolbar in sync with `cd` commands. Each PTY emits
 *
 *   \e]7;file://<host>/<cwd>\e\
 *
 * on every prompt; Terminal.vue's OSC 7 handler parses it and updates the
 * currentCwd ref.
 *
 * Strategy is shell-specific:
 *   bash       — `--rcfile` pointing to a tempfile that sources login profile
 *                (~/.bash_profile / ~/.profile) + ~/.bashrc + adds PROMPT_COMMAND
 *   zsh        — set ZDOTDIR to a tempdir; its .zshrc sources the real one + adds precmd hook
 *   fish       — `--init-command` installs a PWD-change hook after user config loads
 *   powershell — `-NoLogo -NoExit -Command` to load $PROFILE then wrap user's prompt
 *   pwsh       — same as powershell
 *   cmd.exe    — set PROMPT env var with `$E]7;file://...$E\` prefix
 *   other      — no integration (toolbar will only update on focus via ptyGetCwd)
 */
export interface ShellSpec {
  shell: string
  args: string[]
  env: Record<string, string | undefined>
}

function shellName(shellPath: string): string {
  return basename(shellPath)
    .toLowerCase()
    .replace(/\.(exe|cmd|bat)$/, '')
}

function integrationsDir(): string {
  const dir = join(app.getPath('home'), '.troupe', 'integrations')
  mkdirSync(dir, { recursive: true })
  return dir
}

/**
 * 只在内容变化时落盘。startPty 在每个新面板都会调用 shellIntegration,频繁创建
 * 面板会反复 writeFileSync 同一份内容 —— 浪费 I/O,且时间戳变化会被备份/同步
 * 工具看到。这里用 readFileSync 做 idempotent 检查。
 */
function writeIfChanged(path: string, content: string): void {
  try {
    if (existsSync(path) && readFileSync(path, 'utf8') === content) return
  } catch {
    // unreadable — fall through and overwrite
  }
  writeFileSync(path, content)
}

function writeBashRc(): string {
  const path = join(integrationsDir(), 'bash.rc')
  // 用 `--rcfile + -i`,bash 把它当 interactive (非 login) 启动。普通 login shell
  // 才会读 ~/.bash_profile / ~/.profile —— 这两个文件是 macOS 上 nvm/homebrew/
  // /etc/paths.d 的入口。手动 source 一下,否则 GUI 启动的 Troupe 看不到用户的
  // PATH,反映出来就是"在终端里能跑的命令在 Troupe 里 not found"。
  //
  // 用 single-quoted printf format,$HOSTNAME/$PWD 不在 parse 时展开;\033 = ESC,
  // \033\\ = OSC 字符串终止符。
  const content =
    '# Auto-generated by Troupe. Sourced via --rcfile to enable OSC 7 cwd tracking.\n' +
    '# 先模拟 login shell:source 用户的 profile 链,让 PATH/nvm/brew 等 env 入栈。\n' +
    '[ -r ~/.bash_profile ] && source ~/.bash_profile\n' +
    '[ -r ~/.bash_login ] && [ ! -r ~/.bash_profile ] && source ~/.bash_login\n' +
    '[ -r ~/.profile ] && [ ! -r ~/.bash_profile ] && [ ! -r ~/.bash_login ] && source ~/.profile\n' +
    '# 然后是常规 interactive rc。\n' +
    '[ -r ~/.bashrc ] && source ~/.bashrc\n' +
    '__troupe_osc7() {\n' +
    `  printf '\\033]7;file://%s%s\\033\\\\' "\${HOSTNAME:-localhost}" "$PWD"\n` +
    '}\n' +
    `PROMPT_COMMAND="__troupe_osc7\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"\n`
  writeIfChanged(path, content)
  return path
}

function writeZshDir(): string {
  const dir = join(integrationsDir(), 'zsh')
  mkdirSync(dir, { recursive: true })

  // zsh 启动顺序(login interactive):.zshenv → .zprofile → .zshrc → .zlogin。
  // 用 ZDOTDIR 重定向到本目录后,zsh 只看本目录下的对应文件 —— 用户 ~/.zshenv
  // / ~/.zprofile 都不会被加载,后果:
  //   - ~/.zprofile 里设的 PATH(homebrew /opt/homebrew/bin、asdf/nvm shim)
  //     失效 → 子 shell 里 `brew`、`node` 等 not found。
  //   - 主题(oh-my-zsh / starship / p10k)依赖的环境变量缺失 → fallback 到
  //     zsh 内置默认 PROMPT。某些 macOS 版本的默认 PROMPT 不会 ~-substitute,
  //     就出现"路径显示 /Users/foo/projects 而不是 ~/projects"的怪象。
  //
  // 修复方式:在 ZDOTDIR 下放 .zshenv 和 .zprofile wrapper,分别 source 用户
  // 真实文件。$ZDOTDIR_REAL 是 shellIntegration() 提前保存的用户原始 ZDOTDIR
  // (mac 大多数用户没设,fallback 到 $HOME)。
  //
  // .zshrc 里再恢复 ZDOTDIR 给用户后续 cd 用,并装上 OSC 7 hook。.zlogin 用得
  // 极少(login shell 退出前才跑),先不做 wrapper —— 真有用户报 issue 再加。
  const sourceUserFile = (filename: string): string =>
    'if [ -n "$ZDOTDIR_REAL" ]; then\n' +
    `  [ -r "$ZDOTDIR_REAL/${filename}" ] && source "$ZDOTDIR_REAL/${filename}"\n` +
    'else\n' +
    `  [ -r "$HOME/${filename}" ] && source "$HOME/${filename}"\n` +
    'fi\n'

  const zshenv = '# Auto-generated by Troupe.\n' + sourceUserFile('.zshenv')
  const zprofile = '# Auto-generated by Troupe.\n' + sourceUserFile('.zprofile')
  const zshrc =
    '# Auto-generated by Troupe. ZDOTDIR-injected OSC 7 cwd hook.\n' +
    sourceUserFile('.zshrc') +
    // 把 ZDOTDIR 恢复成用户原始值(或 unset),这样用户后续启动子 zsh 不会被
    // 嵌套指到我们的目录。必须在 source 用户 .zshrc 之后做 —— .zshrc 内任何
    // 看 ZDOTDIR 的代码(如 oh-my-zsh 的 `$ZDOTDIR/themes/...`)需要看到我们
    // 重定向之前的值。
    'if [ -n "$ZDOTDIR_REAL" ]; then export ZDOTDIR="$ZDOTDIR_REAL"; else unset ZDOTDIR; fi\n' +
    '__troupe_osc7() {\n' +
    `  printf '\\033]7;file://%s%s\\033\\\\' "\${HOST:-localhost}" "$PWD"\n` +
    '}\n' +
    'typeset -ag precmd_functions\n' +
    'precmd_functions+=(__troupe_osc7)\n'

  writeIfChanged(join(dir, '.zshenv'), zshenv)
  writeIfChanged(join(dir, '.zprofile'), zprofile)
  writeIfChanged(join(dir, '.zshrc'), zshrc)
  return dir
}

/**
 * PowerShell profile-loading 一次性脚本。不再用 -Command 替换用户 prompt,而是:
 *   1. 显式 . $PROFILE  让 oh-my-posh / posh-git / 用户的 alias 都加载
 *   2. 捕获用户当前 prompt 函数引用
 *   3. 用一个新 prompt 包裹它:先打 OSC 7,再调用用户的 prompt
 * 这样用户的视觉提示不变,只是多了一行隐藏的 cwd-notify 序列。
 */
function powershellCommand(): string {
  return [
    // 1) 加载 profile 链。$PROFILE 实际是 CurrentUserCurrentHost 的别名;还需要
    //    AllUsersCurrentHost 才能匹配 PowerShell 自身的启动顺序。
    'if (Test-Path $PROFILE.AllUsersAllHosts) { . $PROFILE.AllUsersAllHosts }',
    'if (Test-Path $PROFILE.AllUsersCurrentHost) { . $PROFILE.AllUsersCurrentHost }',
    'if (Test-Path $PROFILE.CurrentUserAllHosts) { . $PROFILE.CurrentUserAllHosts }',
    'if (Test-Path $PROFILE.CurrentUserCurrentHost) { . $PROFILE.CurrentUserCurrentHost }',
    // 2) 保存用户当前 prompt 函数(可能由 profile 设置 —— oh-my-posh、Starship、…)。
    //    Get-Command prompt 在没自定义时返回内置 Function;Copy 一份引用即可。
    '$global:__troupeOriginalPrompt = (Get-Command prompt).ScriptBlock',
    // 3) 替换 prompt:先打 OSC 7,再调用原 prompt 拿到其返回字符串。
    //    $esc = ESC (0x1B);[char]27 在 Windows PowerShell/PowerShell Core 中一致。
    'function global:prompt {',
    '  $cwd = $ExecutionContext.SessionState.Path.CurrentLocation.Path',
    '  $hn  = if ($env:COMPUTERNAME) { $env:COMPUTERNAME } elseif ($env:HOSTNAME) { $env:HOSTNAME } else { "localhost" }',
    '  $esc = [char]27',
    '  $path = $cwd.Replace([char]92,[char]47)',
    '  if (-not $path.StartsWith("/")) { $path = "/$path" }',
    '  $osc = "$esc]7;file://$hn$path$esc\\"',
    '  $body = if ($global:__troupeOriginalPrompt) { & $global:__troupeOriginalPrompt } else { "PS $cwd> " }',
    '  "$osc$body"',
    '}'
  ].join('; ')
}

function fishCommand(): string {
  return [
    'function __troupe_osc7 --on-variable PWD',
    '  set -l host (hostname)',
    `  printf '\\033]7;file://%s%s\\033\\\\' $host $PWD`,
    'end',
    '__troupe_osc7'
  ].join('; ')
}

export function shellIntegration(shellPath: string): ShellSpec {
  const name = shellName(shellPath)
  const baseEnv: Record<string, string | undefined> = { ...process.env }

  if (name === 'bash') {
    const rc = writeBashRc()
    // `--rcfile` only takes effect for INTERACTIVE bash. Pair it with `-i`
    // explicitly so our hook also wins when the user starts a login shell
    // (`-l`), where bash would otherwise skip rcfiles. `--rcfile` is mutually
    // exclusive with `--login`, so the rcfile itself sources the login profile
    // chain (~/.bash_profile / ~/.profile) up top — see writeBashRc().
    return { shell: shellPath, args: ['--rcfile', rc, '-i'], env: baseEnv }
  }

  if (name === 'zsh') {
    const env = { ...baseEnv }
    if (env.ZDOTDIR) env.ZDOTDIR_REAL = env.ZDOTDIR
    env.ZDOTDIR = writeZshDir()
    return { shell: shellPath, args: ['-l'], env }
  }

  if (name === 'fish') {
    return { shell: shellPath, args: ['-l', '--init-command', fishCommand()], env: baseEnv }
  }

  if (name === 'powershell' || name === 'pwsh' || name === 'pwsh-preview') {
    return {
      shell: shellPath,
      args: ['-NoLogo', '-NoProfile', '-NoExit', '-Command', powershellCommand()],
      env: baseEnv
    }
  }

  if (name === 'cmd') {
    // cmd.exe reads its PROMPT from (in order): the `cmd /K SET PROMPT=...`
    // invocation, then `set` in autorun (HKLM/HKCU\Software\Microsoft\Command
    // Processor\AutoRun), then the inherited env. Setting `env.PROMPT` here
    // covers the inherited-env layer — if a user-level AutoRun overrides it,
    // our OSC 7 prefix is lost. Detecting that case from main would require
    // running cmd and querying back; not worth the complexity for a fallback.
    //
    // $E = ESC, $P = current path, $G = '>'. Prefix the OSC 7 hook to the
    // existing PROMPT (or default `$P$G`) so a user's custom prompt survives.
    //
    // 嵌套启动保护:如果 existing 已经含我们的 OSC 7 hook(用户在 Troupe 内
    // 嵌套启动子 cmd,子 cmd 继承父进程的 PROMPT),不再前置一层,否则每次
    // 嵌套都会让 PROMPT 变长一截。token 用 `]7;file://` 而不是单纯 `]7;`,
    // 避免误碰其它 OSC 9;1/9;9 子代码或 ConEmu 自定义提示。
    const env = { ...baseEnv }
    const host = env.COMPUTERNAME || 'localhost'
    const existing = env.PROMPT && env.PROMPT.length ? env.PROMPT : '$P$G'
    env.PROMPT = existing.includes(']7;file://')
      ? existing
      : `$E]7;file://${host}/$P$E\\${existing}`
    // cmd.exe doesn't have a -l switch; passing it makes cmd open the file
    // named "-l" and fail. The previous code worked only because cmd treats
    // an unrecognised switch as a path and silently ignores the error.
    return { shell: shellPath, args: [], env }
  }

  // Unknown shell — let it run as-is. OSC 7 won't be emitted automatically,
  // but ptyGetCwd on focus still works on Linux/macOS.
  return { shell: shellPath, args: [], env: baseEnv }
}
